---
# Source: auth-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: auth-api-0.1.0
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  name: frontend
spec:
  ports:
  - port: 8080
  selector:
    service: frontend
  type: LoadBalancer
---
# Source: auth-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: auth-api-0.1.0
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-api
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-api
        app.kubernetes.io/instance: test
        service: frontend
    spec:
      containers:
      - env:
        - name: AUTH_API_ADDRESS
          value: http://auth-api:8081
        - name: PORT
          value: "8080"
        - name: TODOS_API_ADDRESS
          value: http://todos-api:8082
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans       
        image: frontend
        name: frontend
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always
