apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
        service: {{ .Values.name }}
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v1/spans
          
        image: {{ .Values.image.repository }}
        name: {{ .Values.name }}
        imagePullPolicy: Never
      restartPolicy: Always
